### ISSUE TITLE
Fails to decompile on latest version of Warzone/ MW

### ISSUE THREAD

**Issue by kibrookfield** [JariKCoding/CoDLuaDecompiler#10]
Exception is thrown at https://github.com/JariKCoding/CoDLuaDecompiler/blob/583ea52aea8bad565d07f2dcf73ec51f9f653855/CoDLuaDecompiler.Decompiler/LuaFile/LuaFileFactory.cs#L27

System.Exception: Invalid file magic

Just briefly looking at the raw data in the LUA file asset, it seems it may now be encrypted.

**Comment by JariKCoding** [comment]
Some files are being compressed in memory. Because I disabled dumping from memory due to the anticheat, I'm not interested in fixing this.
