### ISSUE TITLE
Feature request: Including program name, version, and date in decompiled output files

### ISSUE THREAD

**Issue by Jake-NotTheMuss** [JariKCoding/CoDLuaDecompiler#12]
### Feature

This feature would provide the inclusion of the following data in each file generated by CoDLuaDecompiler:

- Program name used
- Program version
- Decompilation date

The start of each generated file would look something like the following:

```lua
-- Generated by CoDLuaDecompiler
-- Version: <version>
-- Date: <date/time>
```

I'd also like to mention the idea of including Lua function data in the decompiled files, such as:

- Bytecode offset of the function
- Number of parameters
- Number of locals
- Number of upvalues
- Number of immediately nested functions
- Number of instructions

**Comment by JariKCoding** [comment]
Get the extra function data by using `-fs` or `--functionstats` when starting the application from a terminal

**Comment by Jake-NotTheMuss** [comment]
Awesome
